/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculadora;


/**
 *
 * @author anabo
 */
public class visao extends javax.swing.JFrame {

    /**
     * Creates new form visao
     */
    public visao() {
        super("Calculadora");
        initComponents();
    }
    Double valor1, valor2;
    String sinal;
    String linhaCalc;
    //String vet[] = new String[2];

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        visor = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bttAC = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        bttPORCENTAGEM = new javax.swing.JButton();
        bttDIVISAO = new javax.swing.JButton();
        btt7 = new javax.swing.JButton();
        btt8 = new javax.swing.JButton();
        btt9 = new javax.swing.JButton();
        bttMULTIPLICACAO = new javax.swing.JButton();
        btt4 = new javax.swing.JButton();
        btt5 = new javax.swing.JButton();
        btt6 = new javax.swing.JButton();
        bttSUBTRACAO = new javax.swing.JButton();
        btt1 = new javax.swing.JButton();
        btt2 = new javax.swing.JButton();
        btt3 = new javax.swing.JButton();
        bttSOMA = new javax.swing.JButton();
        btt0 = new javax.swing.JButton();
        bttVIRGULA = new javax.swing.JButton();
        bttIGUAL = new javax.swing.JButton();
        bttFECHAR = new javax.swing.JButton();

        jButton6.setText("jButton6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        visor.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        visor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        visor.setText("0");
        visor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visorActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setLayout(new java.awt.GridLayout(5, 4));

        jPanel2.setLayout(new java.awt.GridLayout(5, 4));

        bttAC.setBackground(new java.awt.Color(0, 153, 153));
        bttAC.setForeground(new java.awt.Color(255, 255, 255));
        bttAC.setText("AC");
        bttAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttACActionPerformed(evt);
            }
        });
        jPanel2.add(bttAC);

        jButton21.setBackground(new java.awt.Color(0, 153, 153));
        jButton21.setForeground(new java.awt.Color(255, 255, 255));
        jButton21.setText("+/-");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton21);

        bttPORCENTAGEM.setText("%");
        jPanel2.add(bttPORCENTAGEM);

        bttDIVISAO.setText("/");
        bttDIVISAO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttDIVISAOActionPerformed(evt);
            }
        });
        jPanel2.add(bttDIVISAO);

        btt7.setText("7");
        btt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt7ActionPerformed(evt);
            }
        });
        jPanel2.add(btt7);

        btt8.setText("8");
        btt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt8ActionPerformed(evt);
            }
        });
        jPanel2.add(btt8);

        btt9.setText("9");
        btt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt9ActionPerformed(evt);
            }
        });
        jPanel2.add(btt9);

        bttMULTIPLICACAO.setText("*");
        bttMULTIPLICACAO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttMULTIPLICACAOActionPerformed(evt);
            }
        });
        jPanel2.add(bttMULTIPLICACAO);

        btt4.setText("4");
        btt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt4ActionPerformed(evt);
            }
        });
        jPanel2.add(btt4);

        btt5.setText("5");
        btt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt5ActionPerformed(evt);
            }
        });
        jPanel2.add(btt5);

        btt6.setText("6");
        btt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt6ActionPerformed(evt);
            }
        });
        jPanel2.add(btt6);

        bttSUBTRACAO.setText("-");
        bttSUBTRACAO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSUBTRACAOActionPerformed(evt);
            }
        });
        jPanel2.add(bttSUBTRACAO);

        btt1.setText("1");
        btt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt1ActionPerformed(evt);
            }
        });
        jPanel2.add(btt1);

        btt2.setText("2");
        btt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt2ActionPerformed(evt);
            }
        });
        jPanel2.add(btt2);

        btt3.setText("3");
        btt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt3ActionPerformed(evt);
            }
        });
        jPanel2.add(btt3);

        bttSOMA.setText("+");
        bttSOMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSOMAActionPerformed(evt);
            }
        });
        jPanel2.add(bttSOMA);

        btt0.setText("0");
        btt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt0ActionPerformed(evt);
            }
        });
        jPanel2.add(btt0);

        bttVIRGULA.setText(",");
        bttVIRGULA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttVIRGULAActionPerformed(evt);
            }
        });
        jPanel2.add(bttVIRGULA);

        bttIGUAL.setBackground(new java.awt.Color(0, 153, 153));
        bttIGUAL.setForeground(new java.awt.Color(255, 255, 255));
        bttIGUAL.setText("=");
        bttIGUAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttIGUALActionPerformed(evt);
            }
        });
        jPanel2.add(bttIGUAL);

        bttFECHAR.setText("FECHAR");
        bttFECHAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttFECHARActionPerformed(evt);
            }
        });
        jPanel2.add(bttFECHAR);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(visor)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(visor, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void visorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visorActionPerformed

    private void bttACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttACActionPerformed
        visor.setText("0");
    }//GEN-LAST:event_bttACActionPerformed

    private void bttDIVISAOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttDIVISAOActionPerformed
        //valor1 = Double.parseDouble(visor.getText());
        //visor.setText("");
        visor.setText(visor.getText()+"/");
        sinal = "divisao";
    }//GEN-LAST:event_bttDIVISAOActionPerformed

    private void btt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt7ActionPerformed
        if(visor.getText().equals("0"))
            visor.setText(" ");
        visor.setText(visor.getText()+"7");
    }//GEN-LAST:event_btt7ActionPerformed

    private void btt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt8ActionPerformed
        if(visor.getText().equals("0"))
            visor.setText(" ");
        visor.setText(visor.getText()+"8");
    }//GEN-LAST:event_btt8ActionPerformed

    private void btt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt9ActionPerformed
        if(visor.getText().equals("0"))
            visor.setText(" ");
        visor.setText(visor.getText()+"9");
    }//GEN-LAST:event_btt9ActionPerformed

    private void btt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt4ActionPerformed
        if(visor.getText().equals("0"))
            visor.setText(" ");
        visor.setText(visor.getText()+"4");
    }//GEN-LAST:event_btt4ActionPerformed

    private void btt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt5ActionPerformed
        if(visor.getText().equals("0"))
            visor.setText(" ");
        visor.setText(visor.getText()+"5");
    }//GEN-LAST:event_btt5ActionPerformed

    private void btt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt6ActionPerformed
        if(visor.getText().equals("0"))
            visor.setText(" ");
        visor.setText(visor.getText()+"6");
    }//GEN-LAST:event_btt6ActionPerformed

    private void btt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt1ActionPerformed
        if(visor.getText().equals("0"))
            visor.setText(" ");
        visor.setText(visor.getText()+"1");
    }//GEN-LAST:event_btt1ActionPerformed

    private void btt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt2ActionPerformed
        if(visor.getText().equals("0"))
            visor.setText(" ");
        visor.setText(visor.getText()+"2");
    }//GEN-LAST:event_btt2ActionPerformed

    private void btt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt3ActionPerformed
        if(visor.getText().equals("0"))
            visor.setText(" ");
        visor.setText(visor.getText()+"3");
    }//GEN-LAST:event_btt3ActionPerformed

    private void btt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt0ActionPerformed
        if(visor.getText().equals("0"))
            visor.setText(" ");
        visor.setText(visor.getText()+"0");
    }//GEN-LAST:event_btt0ActionPerformed

    private void bttVIRGULAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttVIRGULAActionPerformed
        visor.setText(visor.getText()+".");
    }//GEN-LAST:event_bttVIRGULAActionPerformed

    private void bttSOMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSOMAActionPerformed
        //valor1 = Double.parseDouble(visor.getText());
        //visor.setText("");
        visor.setText(visor.getText()+"+");
        sinal = "soma";
    }//GEN-LAST:event_bttSOMAActionPerformed

    private void bttIGUALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttIGUALActionPerformed
        //valor2 = Double.parseDouble(visor.getText());
        linhaCalc = visor.getText();
        if(sinal == "soma"){
            String vet[] = linhaCalc.split("\\+");
            valor1 = Double.parseDouble(vet[0]);
            valor2 = Double.parseDouble(vet[1]);
            visor.setText(String.valueOf(valor1+valor2)); //converto o resultado double em  string usando o String.valueOf()
        }
        if(sinal.equals("subtracao")){
            String vet[] = linhaCalc.split("-");
            valor1 = Double.parseDouble(vet[0]);
            valor2 = Double.parseDouble(vet[1]);
            visor.setText(String.valueOf(valor1-valor2)); //converto o resultado double em  string usando o String.valueOf()
        }
        if(sinal == "multiplicacao"){
            String vet[] = linhaCalc.split("\\*");
            valor1 = Double.parseDouble(vet[0]);
            valor2 = Double.parseDouble(vet[1]);
            visor.setText(String.valueOf(valor1*valor2)); //converto o resultado double em  string usando o String.valueOf()
        }
        if(sinal == "divisao"){
            String vet[] = linhaCalc.split("/");
            valor1 = Double.parseDouble(vet[0]);
            valor2 = Double.parseDouble(vet[1]);
            visor.setText(String.valueOf(valor1/valor2)); //converto o resultado double em  string usando o String.valueOf()
        }
        if(sinal == "resto"){
            //EM BREVE NOS CINEMAS
            //visor.setText(String.valueOf(valor1-valor2)); //converto o resultado double em  string usando o String.valueOf()
        }
    }//GEN-LAST:event_bttIGUALActionPerformed

    private void bttSUBTRACAOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSUBTRACAOActionPerformed
        //valor1 = Double.parseDouble(visor.getText());
        //visor.setText("");
        visor.setText(visor.getText()+"-");
        sinal = "subtracao";
    }//GEN-LAST:event_bttSUBTRACAOActionPerformed

    private void bttMULTIPLICACAOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttMULTIPLICACAOActionPerformed
        //valor1 = Double.parseDouble(visor.getText());
        //visor.setText("");
        visor.setText(visor.getText()+"*");
        sinal = "multiplicacao";
    }//GEN-LAST:event_bttMULTIPLICACAOActionPerformed

    private void bttFECHARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttFECHARActionPerformed
        //this.dispose(); 
        System.exit(0);
    }//GEN-LAST:event_bttFECHARActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        /*if(Double.parseDouble(visor.getText()) < 0){
            visor.setText(String.valueOf(Double.parseDouble(visor.getText())*-1));
        }
        else if(Double.parseDouble(visor.getText()) > 0){
            visor.setText(visor.getText());
        }
        else{}*/
        if(Double.parseDouble(visor.getText()) == 0){
        
        }
        else
            visor.setText(String.valueOf(Double.parseDouble(visor.getText())*-1));
        
    }//GEN-LAST:event_jButton21ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(visao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(visao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(visao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(visao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new visao().setVisible(true);
            }
        });
    }
    
    private static void digitar(){
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btt0;
    private javax.swing.JButton btt1;
    private javax.swing.JButton btt2;
    private javax.swing.JButton btt3;
    private javax.swing.JButton btt4;
    private javax.swing.JButton btt5;
    private javax.swing.JButton btt6;
    private javax.swing.JButton btt7;
    private javax.swing.JButton btt8;
    private javax.swing.JButton btt9;
    private javax.swing.JButton bttAC;
    private javax.swing.JButton bttDIVISAO;
    private javax.swing.JButton bttFECHAR;
    private javax.swing.JButton bttIGUAL;
    private javax.swing.JButton bttMULTIPLICACAO;
    private javax.swing.JButton bttPORCENTAGEM;
    private javax.swing.JButton bttSOMA;
    private javax.swing.JButton bttSUBTRACAO;
    private javax.swing.JButton bttVIRGULA;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField visor;
    // End of variables declaration//GEN-END:variables
}
